# query-types = ["single-col-point-query-on-col", "single-col-point-query-on-index", "single-col-mcv-point-on-col", "single-col-mcv-point-on-index"]
query-types = ["single-col-point-query-on-col"]
report-dir = "/Users/zhangyuanjia/Workspace/go/src/github.com/qw4990/OptimizerTester/cetest/test"
analyze-tables = []
n-samples = 100

[[datasets]]
name = "imdb"
db = "imdb"
label = "zipf-1.5"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = ""
label = "ver1"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = ""
label = "ver2"

