report-dir = "/Users/zhangyuanjia/Workspace/go/src/github.com/qw4990/OptimizerTester/cetest/test"
# analyze-tables = ["title", "p-title-hash-production_year", "p-title-range-production_year"]
analyze-tables = []
n-samples = 0 # if it's zero, then test all distinct values
query-type = "single-col-point-query-on-col"
dataset = "imdb"
db = "imdb"

tables = ["title", "p-title-hash-production_year", "p-title-range-production_year"]
labels = ["non-part", "hash/N", "range/N"]

[instance]
addr = "172.16.4.182"
port = 4000
user = "root"
password = ""

