report-dir = "report/pzipfx-PQ-mulcol-index"
# analyze-tables = ["zint", "p_range_zint_a", "p_range_zint_c", "p_hash_zint_a", "p_hash_zint_c"]
analyze-tables = []
n-samples = 0 # if it's zero, then test all distinct values
query-type = "mul-cols-point-query-on-index"
dataset = "pzipfx"
db = "pzipfx"

tables = ["zint", "p_range_zint_a", "p_range_zint_c", "p_hash_zint_a", "p_hash_zint_c"]
labels = ["non-part", "range/Y", "range/N", "hash/Y", "hash/N"]

[instance]
addr = "172.16.4.182"
port = 4000
user = "root"
password = ""

